/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cdp.Conta;
import cdp.Endereco;
import cdp.EstadoConta;
import cdp.EstadosUF;
import cdp.Pessoa;
import cgt.ControleConta;
import cgt.ControlePessoa;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Artur Schaefer<artur.schaefer2 at gmail.com>
 */
public class CadastroCliente extends javax.swing.JFrame {

    //PessoaDAO pesDao = new PessoaDAO();
    ControlePessoa crtlPessoa = new ControlePessoa();
    Pessoa pesAtual = new Pessoa();
    
    public CadastroCliente() {
        initComponents();
        setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setFocusableWindowState(true);

        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJPanel = new javax.swing.JPanel();
        firstJLabel = new javax.swing.JLabel();
        previsJLabel = new javax.swing.JLabel();
        nextJLabel = new javax.swing.JLabel();
        lastJLabel = new javax.swing.JLabel();
        addJLabel = new javax.swing.JLabel();
        updateJLabel = new javax.swing.JLabel();
        searchJLabel = new javax.swing.JLabel();
        delJLabel = new javax.swing.JLabel();
        pessoajPanel = new javax.swing.JPanel();
        nomejLabel = new javax.swing.JLabel();
        cpfjLabel1 = new javax.swing.JLabel();
        rgjLabel2 = new javax.swing.JLabel();
        tel1jLabel3 = new javax.swing.JLabel();
        tel2jLabel4 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        cpfjTextField1 = new javax.swing.JTextField();
        rgjTextField2 = new javax.swing.JTextField();
        tel01jTextField3 = new javax.swing.JTextField();
        tel02jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsjTextArea1 = new javax.swing.JTextArea();
        enderecojPanel1 = new javax.swing.JPanel();
        ufjComboBox1 = new javax.swing.JComboBox<>();
        cidadejLabel5 = new javax.swing.JLabel();
        ufjLabel6 = new javax.swing.JLabel();
        ruajLabel7 = new javax.swing.JLabel();
        bairrojLabel8 = new javax.swing.JLabel();
        cepjLabel9 = new javax.swing.JLabel();
        cidadejTextField5 = new javax.swing.JTextField();
        ruajTextField6 = new javax.swing.JTextField();
        bairrojTextField7 = new javax.swing.JTextField();
        cepjTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Clientes");
        setPreferredSize(new java.awt.Dimension(1024, 600));

        menuJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuJPanel.setPreferredSize(new java.awt.Dimension(900, 95));

        firstJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_first.png"))); // NOI18N
        firstJLabel.setText("Primeiro");
        firstJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstJLabel.setPreferredSize(new java.awt.Dimension(100, 70));
        firstJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstJLabelMouseClicked(evt);
            }
        });

        previsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_previous.png"))); // NOI18N
        previsJLabel.setText("Anterior");
        previsJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previsJLabel.setMaximumSize(new java.awt.Dimension(100, 36));
        previsJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        nextJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_next.png"))); // NOI18N
        nextJLabel.setText("Próximo");
        nextJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nextJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        lastJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_last.png"))); // NOI18N
        lastJLabel.setText("Último");
        lastJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastJLabel.setPreferredSize(new java.awt.Dimension(100, 70));
        lastJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastJLabelMouseClicked(evt);
            }
        });

        addJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addJLabel.setText("Incluir");
        addJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addJLabel.setPreferredSize(new java.awt.Dimension(100, 70));
        addJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addJLabelMouseClicked(evt);
            }
        });

        updateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-mark (1).png"))); // NOI18N
        updateJLabel.setText("Alterar");
        updateJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updateJLabel.setPreferredSize(new java.awt.Dimension(100, 70));
        updateJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateJLabelMouseClicked(evt);
            }
        });

        searchJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        searchJLabel.setText("Pesquisar");
        searchJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchJLabel.setMaximumSize(new java.awt.Dimension(100, 36));
        searchJLabel.setPreferredSize(new java.awt.Dimension(100, 70));
        searchJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchJLabelMouseClicked(evt);
            }
        });

        delJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-icon.png"))); // NOI18N
        delJLabel.setText("Excluir");
        delJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        javax.swing.GroupLayout menuJPanelLayout = new javax.swing.GroupLayout(menuJPanel);
        menuJPanel.setLayout(menuJPanelLayout);
        menuJPanelLayout.setHorizontalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(firstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        menuJPanelLayout.setVerticalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pessoajPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nomejLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        nomejLabel.setText("Nome Completo");

        cpfjLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        cpfjLabel1.setText("CPF");

        rgjLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        rgjLabel2.setText("RG");

        tel1jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tel1jLabel3.setText("Telefone 1");

        tel2jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tel2jLabel4.setText("Telefone 2");

        obsjTextArea1.setColumns(20);
        obsjTextArea1.setRows(5);
        obsjTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(obsjTextArea1);

        javax.swing.GroupLayout pessoajPanelLayout = new javax.swing.GroupLayout(pessoajPanel);
        pessoajPanel.setLayout(pessoajPanelLayout);
        pessoajPanelLayout.setHorizontalGroup(
            pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoajPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addGroup(pessoajPanelLayout.createSequentialGroup()
                        .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfjLabel1)
                            .addComponent(rgjLabel2)
                            .addComponent(tel1jLabel3)
                            .addComponent(tel2jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomejTextField)
                            .addComponent(cpfjTextField1)
                            .addComponent(rgjTextField2)
                            .addComponent(tel01jTextField3)
                            .addComponent(tel02jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pessoajPanelLayout.setVerticalGroup(
            pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoajPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgjLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel01jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel1jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel02jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel2jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        enderecojPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ufjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufjComboBox1ActionPerformed(evt);
            }
        });

        cidadejLabel5.setText("Cidade");

        ufjLabel6.setText("UF");

        ruajLabel7.setText("Rua");

        bairrojLabel8.setText("Bairro");

        cepjLabel9.setText("CEP");

        javax.swing.GroupLayout enderecojPanel1Layout = new javax.swing.GroupLayout(enderecojPanel1);
        enderecojPanel1.setLayout(enderecojPanel1Layout);
        enderecojPanel1Layout.setHorizontalGroup(
            enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecojPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidadejLabel5)
                    .addComponent(ruajLabel7)
                    .addComponent(ufjLabel6)
                    .addComponent(bairrojLabel8)
                    .addComponent(cepjLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidadejTextField5)
                    .addComponent(ruajTextField6)
                    .addComponent(ufjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bairrojTextField7)
                    .addComponent(cepjTextField8))
                .addContainerGap())
        );
        enderecojPanel1Layout.setVerticalGroup(
            enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecojPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadejTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruajTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruajLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairrojTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufjLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecojPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepjTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepjLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pessoajPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecojPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pessoajPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enderecojPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJLabelMouseClicked
        //Antes eu usava um objeto da dao, errou feio... errou rude
        try{
            crtlPessoa.inserirPessoa(lerCampos(0));
            limparCampos();
            JOptionPane.showMessageDialog(this, "Inserido com sucesso!!");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex){
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addJLabelMouseClicked

    private void ufjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufjComboBox1ActionPerformed

    private void searchJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchJLabelMouseClicked
        ListarCliente listarClientes = new ListarCliente(this, true);
        listarClientes.setVisible(true);
        listarClientes.setAlwaysOnTop(true);

        try {
            pesAtual = listarClientes.getPessoaSelecionada();
            pesAtual = crtlPessoa.listarPessoas(2,pesAtual.getCpf()).get(0);
            inserirPessoaDoBanco(pesAtual);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarClientes.dispose();
    }//GEN-LAST:event_searchJLabelMouseClicked

    private void firstJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstJLabelMouseClicked
        try {
            pegaPosicao(0);//PRIMEIRO DA LISTA
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_firstJLabelMouseClicked

    private void lastJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastJLabelMouseClicked
        try {
            pegaPosicao(1);//ULTIMO DA LISTA
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_lastJLabelMouseClicked

    private void updateJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateJLabelMouseClicked
         try{
            pesAtual = lerCampos(1);
             
            crtlPessoa.alterarPessoa(pesAtual);
            limparCampos();
            JOptionPane.showMessageDialog(this, "Alterado com sucesso!!");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex){
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateJLabelMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addJLabel;
    private javax.swing.JLabel bairrojLabel8;
    private javax.swing.JTextField bairrojTextField7;
    private javax.swing.JLabel cepjLabel9;
    private javax.swing.JTextField cepjTextField8;
    private javax.swing.JLabel cidadejLabel5;
    private javax.swing.JTextField cidadejTextField5;
    private javax.swing.JLabel cpfjLabel1;
    private javax.swing.JTextField cpfjTextField1;
    private javax.swing.JLabel delJLabel;
    private javax.swing.JPanel enderecojPanel1;
    private javax.swing.JLabel firstJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastJLabel;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JLabel nextJLabel;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextArea obsjTextArea1;
    private javax.swing.JPanel pessoajPanel;
    private javax.swing.JLabel previsJLabel;
    private javax.swing.JLabel rgjLabel2;
    private javax.swing.JTextField rgjTextField2;
    private javax.swing.JLabel ruajLabel7;
    private javax.swing.JTextField ruajTextField6;
    private javax.swing.JLabel searchJLabel;
    private javax.swing.JTextField tel01jTextField3;
    private javax.swing.JTextField tel02jTextField4;
    private javax.swing.JLabel tel1jLabel3;
    private javax.swing.JLabel tel2jLabel4;
    private javax.swing.JComboBox<String> ufjComboBox1;
    private javax.swing.JLabel ufjLabel6;
    private javax.swing.JLabel updateJLabel;
    // End of variables declaration//GEN-END:variables
    
    public  Pessoa lerCampos(int op) throws SQLException{
        try {
            Pessoa pes = new Pessoa();
            pes.setCpf(cpfjTextField1.getText());
            pes.setNome(nomejTextField.getText());
            pes.setRg(rgjTextField2.getText());
            pes.setTelefone01(Integer.parseUnsignedInt(tel01jTextField3.getText()));
            pes.setTelefone02(Integer.parseUnsignedInt(tel02jTextField4.getText()));
            pes.setObservacoes(obsjTextArea1.getText());

            Endereco end = new Endereco();
            end.setBairro(bairrojTextField7.getText());
            end.setCep(Integer.parseUnsignedInt(cepjTextField8.getText()));
            end.setCidade(cidadejTextField5.getText());
            end.setRua(ruajTextField6.getText());
            end.setEstado(ufjComboBox1.getSelectedItem().toString());

            pes.setEndereco(end);

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate localDate = LocalDate.now();
            
            Conta conta = new Conta();
            if (op == 0){ //Insert
                conta.setAbertaEm(localDate.toString());
                conta.setSituacao(EstadoConta.ATIVO);
                conta.setFechadaEm(null);
            }else { //Update ou delete
                conta = new ControleConta().listarContas(0, pes.getCpf()).get(0);
            }
            conta.setPessoa(pes);

            pes.setConta(conta);
            return pes;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Algum campo está vazio!!");
        }
        return null;
    }

    private void limparCampos() {
        cpfjTextField1.setText("");
        nomejTextField.setText("");
        cepjTextField8.setText("");
        rgjTextField2.setText("");
        tel01jTextField3.setText("");
        tel02jTextField4.setText("");
        ruajTextField6.setText("");
        cepjTextField8.setText("");
        bairrojTextField7.setText("");
        cidadejTextField5.setText("");
        obsjTextArea1.setText("");
    }
    
    public void pegaPosicao(int pos) throws SQLException{
        List<Pessoa> pesLista = null;
        Pessoa pes = new Pessoa();
        switch(pos){
            case 0://PRIMEIRO CLIENTE
                pesLista = crtlPessoa.listarPessoas(1, "");
                pesAtual = pesLista.get(pos);
                break;
            case 1://ULTIMO DA LISTA
                pesLista = crtlPessoa.listarPessoas(1, "");
                pesAtual = pesLista.get(pesLista.size()-1);
                break;
        }
        
        inserirPessoaDoBanco(pes);
    }
    
    public void inserirPessoaDoBanco(Pessoa pes) throws SQLException{
        cpfjTextField1.setText(pesAtual.getCpf());
        nomejTextField.setText(pesAtual.getNome());
        rgjTextField2.setText(pesAtual.getRg());
        tel01jTextField3.setText(Integer.toString(pesAtual.getTelefone01()));
        tel02jTextField4.setText(Integer.toString(pesAtual.getTelefone02()));
        
        ruajTextField6.setText(pesAtual.getEndereco().getRua());
        bairrojTextField7.setText(pesAtual.getEndereco().getBairro());
        cidadejTextField5.setText(pesAtual.getEndereco().getCidade());
        obsjTextArea1.setText(pesAtual.getObservacoes());
        ufjComboBox1.setSelectedItem(pesAtual.getEndereco().getEstado());
        cepjTextField8.setText(Integer.toString(pesAtual.getEndereco().getCep()));        
    }
    
    public void preencherCombo(){
        ufjComboBox1.addItem(EstadosUF.ES.toString());
        ufjComboBox1.addItem(EstadosUF.MG.toString());
        ufjComboBox1.addItem(EstadosUF.SP.toString());
        ufjComboBox1.addItem(EstadosUF.RJ.toString());
    }
}
