package cih;

import javax.swing.JFrame;

/**
 *
 * @author Artur Schaefer<artur.schaefer2 at gmail.com>
 */

/*
 * Autor:           Artur Schaefer<artur.schaefer2 at gmail.com>
 * Data:            20/09/2016
 * Hora:            14:57:59
 * Codificação:     UTF-8 
 * Disciplina:      Programação Orientada a Objetos II
 * Professor:       Jean Glazar
 * Instituição:     Instituto Federal de Educação, Ciência e Tecnologia do Espírito Santo - IFES
 *
 * Nome Original:       Calculadora
 * Pacote de Criação:   cih
 */
public class Calculadora extends JFrame{

    /**
     * Creates new form Calculadora
     */
    private static Calculadora instancia;
    
    private Calculadora() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public static synchronized Calculadora getInstance(){
        if (instancia == null){
            instancia = new Calculadora();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onejButton = new javax.swing.JButton();
        openParenjButton = new javax.swing.JButton();
        twojButton = new javax.swing.JButton();
        closeParenjButton = new javax.swing.JButton();
        threejButton = new javax.swing.JButton();
        xjButton = new javax.swing.JButton();
        minusjButton = new javax.swing.JButton();
        sqrtjButton = new javax.swing.JButton();
        cejButton = new javax.swing.JButton();
        zerojButton = new javax.swing.JButton();
        equaljButton = new javax.swing.JButton();
        plusjButton = new javax.swing.JButton();
        commajButton = new javax.swing.JButton();
        expressionjTextField = new javax.swing.JTextField();
        sevenjButton = new javax.swing.JButton();
        eightjButton = new javax.swing.JButton();
        ninejButton = new javax.swing.JButton();
        divjButton = new javax.swing.JButton();
        fivejButton = new javax.swing.JButton();
        fourjButton = new javax.swing.JButton();
        sixjButton = new javax.swing.JButton();
        percentjButton = new javax.swing.JButton();
        multjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        onejButton.setText("1");
        onejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onejButtonActionPerformed(evt);
            }
        });

        openParenjButton.setText("(");
        openParenjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openParenjButtonActionPerformed(evt);
            }
        });

        twojButton.setText("2");
        twojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twojButtonActionPerformed(evt);
            }
        });

        closeParenjButton.setText(")");
        closeParenjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeParenjButtonActionPerformed(evt);
            }
        });

        threejButton.setText("3");
        threejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threejButtonActionPerformed(evt);
            }
        });

        xjButton.setText("x²");
        xjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjButtonActionPerformed(evt);
            }
        });

        minusjButton.setText("-");
        minusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusjButtonActionPerformed(evt);
            }
        });

        sqrtjButton.setText("√ ");
        sqrtjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtjButtonActionPerformed(evt);
            }
        });

        cejButton.setText("CE");
        cejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cejButtonActionPerformed(evt);
            }
        });

        zerojButton.setText("0");
        zerojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerojButtonActionPerformed(evt);
            }
        });

        equaljButton.setText("=");
        equaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equaljButtonActionPerformed(evt);
            }
        });

        plusjButton.setText("+");
        plusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusjButtonActionPerformed(evt);
            }
        });

        commajButton.setText(",");
        commajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commajButtonActionPerformed(evt);
            }
        });

        expressionjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expressionjTextFieldMouseClicked(evt);
            }
        });

        sevenjButton.setText("7");
        sevenjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenjButtonActionPerformed(evt);
            }
        });

        eightjButton.setText("8");
        eightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightjButtonActionPerformed(evt);
            }
        });

        ninejButton.setText("9");
        ninejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninejButtonActionPerformed(evt);
            }
        });

        divjButton.setText("÷");
        divjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divjButtonActionPerformed(evt);
            }
        });

        fivejButton.setText("5");
        fivejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivejButtonActionPerformed(evt);
            }
        });

        fourjButton.setText("4");
        fourjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourjButtonActionPerformed(evt);
            }
        });

        sixjButton.setText("6");
        sixjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixjButtonActionPerformed(evt);
            }
        });

        percentjButton.setText("%");
        percentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentjButtonActionPerformed(evt);
            }
        });

        multjButton.setText("x");
        multjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zerojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(commajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sevenjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eightjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(onejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fourjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fivejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ninejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sixjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(threejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(percentjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(multjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minusjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plusjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(openParenjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(closeParenjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(sqrtjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(cejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(equaljButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(expressionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expressionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenjButton)
                            .addComponent(eightjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourjButton)
                            .addComponent(fivejButton))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onejButton)
                            .addComponent(twojButton)
                            .addComponent(threejButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zerojButton)
                            .addComponent(commajButton)
                            .addComponent(percentjButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ninejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sixjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divjButton)
                            .addComponent(cejButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multjButton)
                            .addComponent(openParenjButton)
                            .addComponent(closeParenjButton))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minusjButton)
                            .addComponent(xjButton)
                            .addComponent(sqrtjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plusjButton)
                            .addComponent(equaljButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //expressionjTextField.setText("Nenhuma expressão inserida!");
    }//GEN-LAST:event_formWindowOpened

    private void expressionjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expressionjTextFieldMouseClicked
        expressionjTextField.setText("");
    }//GEN-LAST:event_expressionjTextFieldMouseClicked

    private void cejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cejButtonActionPerformed
        expressionjTextField.setText("");
    }//GEN-LAST:event_cejButtonActionPerformed

    private void sevenjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"7");
    }//GEN-LAST:event_sevenjButtonActionPerformed

    private void eightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"8");
    }//GEN-LAST:event_eightjButtonActionPerformed

    private void ninejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninejButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"9");
    }//GEN-LAST:event_ninejButtonActionPerformed

    private void fourjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"4");
    }//GEN-LAST:event_fourjButtonActionPerformed

    private void fivejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivejButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"5");
    }//GEN-LAST:event_fivejButtonActionPerformed

    private void sixjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"6");
    }//GEN-LAST:event_sixjButtonActionPerformed

    private void onejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onejButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"1");
    }//GEN-LAST:event_onejButtonActionPerformed

    private void twojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twojButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"2");
    }//GEN-LAST:event_twojButtonActionPerformed

    private void threejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threejButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"3");
    }//GEN-LAST:event_threejButtonActionPerformed

    private void zerojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerojButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"0");
    }//GEN-LAST:event_zerojButtonActionPerformed

    private void commajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commajButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+",");
    }//GEN-LAST:event_commajButtonActionPerformed

    private void percentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"%");
    }//GEN-LAST:event_percentjButtonActionPerformed

    private void divjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"/");
    }//GEN-LAST:event_divjButtonActionPerformed

    private void multjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"*");
    }//GEN-LAST:event_multjButtonActionPerformed

    private void minusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"-");
    }//GEN-LAST:event_minusjButtonActionPerformed

    private void plusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"+");
    }//GEN-LAST:event_plusjButtonActionPerformed

    private void openParenjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openParenjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"(");
    }//GEN-LAST:event_openParenjButtonActionPerformed

    private void closeParenjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeParenjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+")");
    }//GEN-LAST:event_closeParenjButtonActionPerformed

    private void xjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"^");
    }//GEN-LAST:event_xjButtonActionPerformed

    private void sqrtjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtjButtonActionPerformed
        expressionjTextField.setText(expressionjTextField.getText()+"^1/2");
    }//GEN-LAST:event_sqrtjButtonActionPerformed

    private void equaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equaljButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equaljButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cejButton;
    private javax.swing.JButton closeParenjButton;
    private javax.swing.JButton commajButton;
    private javax.swing.JButton divjButton;
    private javax.swing.JButton eightjButton;
    private javax.swing.JButton equaljButton;
    private javax.swing.JTextField expressionjTextField;
    private javax.swing.JButton fivejButton;
    private javax.swing.JButton fourjButton;
    private javax.swing.JButton minusjButton;
    private javax.swing.JButton multjButton;
    private javax.swing.JButton ninejButton;
    private javax.swing.JButton onejButton;
    private javax.swing.JButton openParenjButton;
    private javax.swing.JButton percentjButton;
    private javax.swing.JButton plusjButton;
    private javax.swing.JButton sevenjButton;
    private javax.swing.JButton sixjButton;
    private javax.swing.JButton sqrtjButton;
    private javax.swing.JButton threejButton;
    private javax.swing.JButton twojButton;
    private javax.swing.JButton xjButton;
    private javax.swing.JButton zerojButton;
    // End of variables declaration//GEN-END:variables
}


/*
 *  O programa é de uso exclusivo para a disciplina de Programação Orientada a Objetos II
 *  Sua cópia é estritamente proibida!
 *  Na dúvida entre em contato: artur.schaefer2@gmail.com
 *  ©Artur_Schaefer
 */
