/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;
import javax.swing.JFrame;

/**
 *
 * @author artur
 */
public class Home extends javax.swing.JFrame {
    private String nomeEntrada;
    private String senhaEntrada;
 
    public Home(String nomeEntrada, String senhaEntrada) {
        this.nomeEntrada = nomeEntrada;
        this.senhaEntrada = senhaEntrada;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        setVisible(true);
        exitJButton.setVisible(true);        
    }
    
    /**
     * 
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        setVisible(true);
        exitJButton.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitJButton = new javax.swing.JButton();
        painelAtalhos = new javax.swing.JPanel();
        toolsjLabel = new javax.swing.JLabel();
        employersJLabel = new javax.swing.JLabel();
        mudasJLabel = new javax.swing.JLabel();
        clientsJLabel = new javax.swing.JLabel();
        salesJLabel = new javax.swing.JLabel();
        calcJLabel = new javax.swing.JLabel();
        calendarJLabel = new javax.swing.JLabel();
        sairJLabel = new javax.swing.JLabel();
        logoJPanel = new javax.swing.JPanel();
        logoJLabel = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        financeiroJMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        vendasJMenuItem = new javax.swing.JMenuItem();
        cadastroJMenu = new javax.swing.JMenu();
        clientsJMenuItem = new javax.swing.JMenuItem();
        employersJMenuItem = new javax.swing.JMenuItem();
        viveiroJMenuItem = new javax.swing.JMenuItem();
        insumoJMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        reportsJMenu = new javax.swing.JMenu();
        utilitiesJMenu = new javax.swing.JMenu();
        calendarjCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        calcjMenuItem = new javax.swing.JMenuItem();
        informationJMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mudas Schaefer");
        setLocationByPlatform(true);
        setName("homeFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1366, 768));

        exitJButton.setText("Sair");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        painelAtalhos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelAtalhos.setPreferredSize(new java.awt.Dimension(1366, 110));

        toolsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toolsjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/toolbox.png"))); // NOI18N
        toolsjLabel.setText("Equipamentos");
        toolsjLabel.setToolTipText("Gerencia de equipamentos");
        toolsjLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolsjLabel.setMaximumSize(new java.awt.Dimension(150, 80));
        toolsjLabel.setMinimumSize(new java.awt.Dimension(130, 80));
        toolsjLabel.setPreferredSize(new java.awt.Dimension(140, 75));

        employersJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employersJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reseller_programm.png"))); // NOI18N
        employersJLabel.setText("Funcionários");
        employersJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        employersJLabel.setMaximumSize(new java.awt.Dimension(130, 80));
        employersJLabel.setMinimumSize(new java.awt.Dimension(130, 80));
        employersJLabel.setPreferredSize(new java.awt.Dimension(140, 75));

        mudasJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mudasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tree.png"))); // NOI18N
        mudasJLabel.setText("Mudas");
        mudasJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mudasJLabel.setPreferredSize(new java.awt.Dimension(130, 80));

        clientsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        clientsJLabel.setText("Clientes");
        clientsJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clientsJLabel.setPreferredSize(new java.awt.Dimension(130, 80));
        clientsJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientsJLabelMousePressed(evt);
            }
        });

        salesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        salesJLabel.setText("Vendas");
        salesJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salesJLabel.setPreferredSize(new java.awt.Dimension(130, 80));

        calcJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator_black.png"))); // NOI18N
        calcJLabel.setText("Calculadora");
        calcJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calcJLabel.setPreferredSize(new java.awt.Dimension(130, 80));
        calcJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcJLabelMouseClicked(evt);
            }
        });

        calendarJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        calendarJLabel.setText("Calendário");
        calendarJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calendarJLabel.setPreferredSize(new java.awt.Dimension(130, 80));

        sairJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sairJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control_power_blue.png"))); // NOI18N
        sairJLabel.setText("Sair");
        sairJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sairJLabel.setPreferredSize(new java.awt.Dimension(130, 80));
        sairJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairJLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelAtalhosLayout = new javax.swing.GroupLayout(painelAtalhos);
        painelAtalhos.setLayout(painelAtalhosLayout);
        painelAtalhosLayout.setHorizontalGroup(
            painelAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtalhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employersJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mudasJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelAtalhosLayout.setVerticalGroup(
            painelAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAtalhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employersJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mudasJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calcJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calendarJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toolsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        logoJPanel.setPreferredSize(new java.awt.Dimension(1366, 152));

        logoJLabel.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        logoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/muda.png"))); // NOI18N
        logoJLabel.setText("Viveiro Schaefer");

        javax.swing.GroupLayout logoJPanelLayout = new javax.swing.GroupLayout(logoJPanel);
        logoJPanel.setLayout(logoJPanelLayout);
        logoJPanelLayout.setHorizontalGroup(
            logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoJPanelLayout.createSequentialGroup()
                .addComponent(logoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoJPanelLayout.setVerticalGroup(
            logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barraMenu.setBackground(java.awt.Color.lightGray);
        barraMenu.setForeground(java.awt.SystemColor.desktop);

        financeiroJMenu.setText("Financeiro");
        financeiroJMenu.setToolTipText("Vendas, Pendências...");

        jMenuItem2.setText("Pagamentos");
        financeiroJMenu.add(jMenuItem2);

        vendasJMenuItem.setText("Vendas");
        financeiroJMenu.add(vendasJMenuItem);

        barraMenu.add(financeiroJMenu);

        cadastroJMenu.setText("Cadastros");
        cadastroJMenu.setToolTipText("Clientes, Transportadoras, Funcionários...");

        clientsJMenuItem.setText("Clientes");
        clientsJMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientsJMenuItemMouseClicked(evt);
            }
        });
        clientsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsJMenuItemActionPerformed(evt);
            }
        });
        cadastroJMenu.add(clientsJMenuItem);

        employersJMenuItem.setText("Funcionários");
        employersJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employersJMenuItemActionPerformed(evt);
            }
        });
        cadastroJMenu.add(employersJMenuItem);

        viveiroJMenuItem.setText("Viveiro");
        viveiroJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viveiroJMenuItemActionPerformed(evt);
            }
        });
        cadastroJMenu.add(viveiroJMenuItem);

        insumoJMenuItem.setText("Insumo");
        cadastroJMenu.add(insumoJMenuItem);

        jMenuItem1.setText("Equipamentos");
        cadastroJMenu.add(jMenuItem1);

        barraMenu.add(cadastroJMenu);

        reportsJMenu.setText("Relatórios");
        reportsJMenu.setToolTipText("Vendas, Gastos...");
        barraMenu.add(reportsJMenu);

        utilitiesJMenu.setText("Utilitários");
        utilitiesJMenu.setToolTipText("Calculadora, Calendário...");

        calendarjCheckBoxMenuItem.setSelected(true);
        calendarjCheckBoxMenuItem.setText("Calendário");
        utilitiesJMenu.add(calendarjCheckBoxMenuItem);

        calcjMenuItem.setText("Calculadora");
        utilitiesJMenu.add(calcjMenuItem);

        barraMenu.add(utilitiesJMenu);

        informationJMenu.setText("Informações");
        informationJMenu.setToolTipText("Sobre o Software, Desenvolvedor...");

        aboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenu.setText("Sobre");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        informationJMenu.add(aboutMenu);

        barraMenu.add(informationJMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitJButton)
                        .addGap(0, 1309, Short.MAX_VALUE))
                    .addComponent(painelAtalhos, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(logoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(exitJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        Informacao info = new Informacao();
        info.setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void clientsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsJMenuItemActionPerformed
        
    }//GEN-LAST:event_clientsJMenuItemActionPerformed

    private void employersJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employersJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employersJMenuItemActionPerformed

    private void viveiroJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viveiroJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viveiroJMenuItemActionPerformed

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void sairJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairJLabelMouseClicked
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_sairJLabelMouseClicked

    private void clientsJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsJLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientsJLabelMousePressed

    private void clientsJMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsJMenuItemMouseClicked
    }//GEN-LAST:event_clientsJMenuItemMouseClicked

    private void calcJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcJLabelMouseClicked
        Calculadora.getInstance().setVisible(true);
    }//GEN-LAST:event_calcJLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu cadastroJMenu;
    private javax.swing.JLabel calcJLabel;
    private javax.swing.JMenuItem calcjMenuItem;
    private javax.swing.JLabel calendarJLabel;
    private javax.swing.JCheckBoxMenuItem calendarjCheckBoxMenuItem;
    private javax.swing.JLabel clientsJLabel;
    private javax.swing.JMenuItem clientsJMenuItem;
    private javax.swing.JLabel employersJLabel;
    private javax.swing.JMenuItem employersJMenuItem;
    private javax.swing.JButton exitJButton;
    private javax.swing.JMenu financeiroJMenu;
    private javax.swing.JMenu informationJMenu;
    private javax.swing.JMenuItem insumoJMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JPanel logoJPanel;
    private javax.swing.JLabel mudasJLabel;
    private javax.swing.JPanel painelAtalhos;
    private javax.swing.JMenu reportsJMenu;
    private javax.swing.JLabel sairJLabel;
    private javax.swing.JLabel salesJLabel;
    private javax.swing.JLabel toolsjLabel;
    private javax.swing.JMenu utilitiesJMenu;
    private javax.swing.JMenuItem vendasJMenuItem;
    private javax.swing.JMenuItem viveiroJMenuItem;
    // End of variables declaration//GEN-END:variables
}
