/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

/**
 *
 * @author Artur Schaefer<artur.schaefer2 at gmail.com>
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJPanel2 = new javax.swing.JPanel();
        firstJLabel2 = new javax.swing.JLabel();
        previsJLabel2 = new javax.swing.JLabel();
        nextJLabel2 = new javax.swing.JLabel();
        lastJLabel2 = new javax.swing.JLabel();
        addJLabel2 = new javax.swing.JLabel();
        updateJLabel2 = new javax.swing.JLabel();
        searchJLabel2 = new javax.swing.JLabel();
        delJLabel2 = new javax.swing.JLabel();
        geraljPanel1 = new javax.swing.JPanel();
        clientejPanel2 = new javax.swing.JPanel();
        nomejTextField1 = new javax.swing.JTextField();
        cpfjTextField2 = new javax.swing.JTextField();
        rgjTextField3 = new javax.swing.JTextField();
        tel1jTextField4 = new javax.swing.JTextField();
        tel2jTextField5 = new javax.swing.JTextField();
        nfjTextField6 = new javax.swing.JTextField();
        dataComprajTextField1 = new javax.swing.JTextField();
        dataEntregajTextField2 = new javax.swing.JTextField();
        valorTotaljTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuJPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuJPanel2.setPreferredSize(new java.awt.Dimension(900, 95));

        firstJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_first.png"))); // NOI18N
        firstJLabel2.setText("Primeiro");
        firstJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstJLabel2.setMaximumSize(new java.awt.Dimension(100, 36));
        firstJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        previsJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previsJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_previous.png"))); // NOI18N
        previsJLabel2.setText("Anterior");
        previsJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previsJLabel2.setMaximumSize(new java.awt.Dimension(100, 36));
        previsJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        nextJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_next.png"))); // NOI18N
        nextJLabel2.setText("Próximo");
        nextJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nextJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        lastJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_last.png"))); // NOI18N
        lastJLabel2.setText("Último");
        lastJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        addJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addJLabel2.setText("Incluir");
        addJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        updateJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-mark (1).png"))); // NOI18N
        updateJLabel2.setText("Alterar");
        updateJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updateJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        searchJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        searchJLabel2.setText("Pesquisar");
        searchJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchJLabel2.setMaximumSize(new java.awt.Dimension(100, 36));
        searchJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        delJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-icon.png"))); // NOI18N
        delJLabel2.setText("Excluir");
        delJLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delJLabel2.setPreferredSize(new java.awt.Dimension(100, 70));

        javax.swing.GroupLayout menuJPanel2Layout = new javax.swing.GroupLayout(menuJPanel2);
        menuJPanel2.setLayout(menuJPanel2Layout);
        menuJPanel2Layout.setHorizontalGroup(
            menuJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(firstJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previsJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuJPanel2Layout.setVerticalGroup(
            menuJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previsJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientejPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nomejTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Cliente"));

        cpfjTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));

        rgjTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("RG"));

        tel1jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone 1"));

        tel2jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone 2"));

        nfjTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder("NF"));

        dataComprajTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data da compra"));

        dataEntregajTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de envio"));

        valorTotaljTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor total"));

        javax.swing.GroupLayout clientejPanel2Layout = new javax.swing.GroupLayout(clientejPanel2);
        clientejPanel2.setLayout(clientejPanel2Layout);
        clientejPanel2Layout.setHorizontalGroup(
            clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientejPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientejPanel2Layout.createSequentialGroup()
                        .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomejTextField1)
                            .addComponent(tel1jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(nfjTextField6))
                        .addGap(18, 18, 18)
                        .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientejPanel2Layout.createSequentialGroup()
                                .addComponent(dataComprajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataEntregajTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clientejPanel2Layout.createSequentialGroup()
                                .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tel2jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rgjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(valorTotaljTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientejPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cpfjTextField2, dataComprajTextField1, dataEntregajTextField2, rgjTextField3, tel2jTextField5});

        clientejPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nfjTextField6, nomejTextField1, tel1jTextField4, valorTotaljTextField3});

        clientejPanel2Layout.setVerticalGroup(
            clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientejPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel2jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel1jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientejPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataComprajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataEntregajTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nfjTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorTotaljTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Nome ", "Valor unitário", "Quantidade", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout geraljPanel1Layout = new javax.swing.GroupLayout(geraljPanel1);
        geraljPanel1.setLayout(geraljPanel1Layout);
        geraljPanel1Layout.setHorizontalGroup(
            geraljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientejPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        geraljPanel1Layout.setVerticalGroup(
            geraljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geraljPanel1Layout.createSequentialGroup()
                .addComponent(clientejPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
            .addComponent(geraljPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geraljPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addJLabel2;
    private javax.swing.JPanel clientejPanel2;
    private javax.swing.JTextField cpfjTextField2;
    private javax.swing.JTextField dataComprajTextField1;
    private javax.swing.JTextField dataEntregajTextField2;
    private javax.swing.JLabel delJLabel2;
    private javax.swing.JLabel firstJLabel2;
    private javax.swing.JPanel geraljPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastJLabel2;
    private javax.swing.JPanel menuJPanel2;
    private javax.swing.JLabel nextJLabel2;
    private javax.swing.JTextField nfjTextField6;
    private javax.swing.JTextField nomejTextField1;
    private javax.swing.JLabel previsJLabel2;
    private javax.swing.JTextField rgjTextField3;
    private javax.swing.JLabel searchJLabel2;
    private javax.swing.JTextField tel1jTextField4;
    private javax.swing.JTextField tel2jTextField5;
    private javax.swing.JLabel updateJLabel2;
    private javax.swing.JTextField valorTotaljTextField3;
    // End of variables declaration//GEN-END:variables
}
