/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desabilitado;

/**
 *
 * @author Artur
 */
public class CadastroLoteMudas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLoteMudas
     */
    public CadastroLoteMudas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJPanel = new javax.swing.JPanel();
        firstJLabel = new javax.swing.JLabel();
        previsJLabel = new javax.swing.JLabel();
        nextJLabel = new javax.swing.JLabel();
        lastJLabel = new javax.swing.JLabel();
        addJLabel = new javax.swing.JLabel();
        updateJLabel = new javax.swing.JLabel();
        searchJLabel = new javax.swing.JLabel();
        delJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cadastroMudasjButton1 = new javax.swing.JButton();
        mudajLabel1 = new javax.swing.JLabel();
        mudajComboBox1 = new javax.swing.JComboBox<>();
        viveirojLabel2 = new javax.swing.JLabel();
        viveirojComboBox2 = new javax.swing.JComboBox<>();
        cadastroViveirojButton2 = new javax.swing.JButton();
        qntjLabel3 = new javax.swing.JLabel();
        qntjTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuJPanel.setPreferredSize(new java.awt.Dimension(900, 95));

        firstJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_first.png"))); // NOI18N
        firstJLabel.setText("Primeiro");
        firstJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstJLabel.setMaximumSize(new java.awt.Dimension(100, 36));
        firstJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        previsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_previous.png"))); // NOI18N
        previsJLabel.setText("Anterior");
        previsJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previsJLabel.setEnabled(false);
        previsJLabel.setMaximumSize(new java.awt.Dimension(100, 36));
        previsJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        nextJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_next.png"))); // NOI18N
        nextJLabel.setText("Próximo");
        nextJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nextJLabel.setEnabled(false);
        nextJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        lastJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultset_last.png"))); // NOI18N
        lastJLabel.setText("Último");
        lastJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        addJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addJLabel.setText("Incluir");
        addJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        updateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-mark (1).png"))); // NOI18N
        updateJLabel.setText("Alterar");
        updateJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updateJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        searchJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        searchJLabel.setText("Pesquisar");
        searchJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchJLabel.setMaximumSize(new java.awt.Dimension(100, 36));
        searchJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        delJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-icon.png"))); // NOI18N
        delJLabel.setText("Excluir");
        delJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delJLabel.setPreferredSize(new java.awt.Dimension(100, 70));

        javax.swing.GroupLayout menuJPanelLayout = new javax.swing.GroupLayout(menuJPanel);
        menuJPanel.setLayout(menuJPanelLayout);
        menuJPanelLayout.setHorizontalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(firstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuJPanelLayout.setVerticalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroMudasjButton1.setText("Cadastrar Mudas?");

        mudajLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mudajLabel1.setText("Tipo da Muda");

        viveirojLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viveirojLabel2.setText("Viveiro");

        cadastroViveirojButton2.setText("Cadastro de Viveiro?");

        qntjLabel3.setText("Quantidade de Mudas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(qntjLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qntjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mudajLabel1)
                            .addComponent(viveirojLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mudajComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viveirojComboBox2, 0, 184, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastroViveirojButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroMudasjButton1)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cadastroMudasjButton1, cadastroViveirojButton2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mudajComboBox1, mudajLabel1, qntjLabel3, qntjTextField1, viveirojComboBox2, viveirojLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mudajLabel1)
                    .addComponent(mudajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viveirojLabel2)
                    .addComponent(viveirojComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroMudasjButton1)
                    .addComponent(cadastroViveirojButton2)
                    .addComponent(qntjLabel3)
                    .addComponent(qntjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mudajComboBox1, mudajLabel1, viveirojComboBox2, viveirojLabel2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLoteMudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLoteMudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLoteMudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLoteMudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLoteMudas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addJLabel;
    private javax.swing.JButton cadastroMudasjButton1;
    private javax.swing.JButton cadastroViveirojButton2;
    private javax.swing.JLabel delJLabel;
    private javax.swing.JLabel firstJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastJLabel;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JComboBox<String> mudajComboBox1;
    private javax.swing.JLabel mudajLabel1;
    private javax.swing.JLabel nextJLabel;
    private javax.swing.JLabel previsJLabel;
    private javax.swing.JLabel qntjLabel3;
    private javax.swing.JTextField qntjTextField1;
    private javax.swing.JLabel searchJLabel;
    private javax.swing.JLabel updateJLabel;
    private javax.swing.JComboBox<String> viveirojComboBox2;
    private javax.swing.JLabel viveirojLabel2;
    // End of variables declaration//GEN-END:variables
}
